export interface QuotationHdr {
ctqhId: string,
ctqhDate: Date,
ctqhType: string,
ctqhStatus: string,
ctqhSendDate: Date,
ctqhCcustCusno: string,
ctqhPic1Cusno:string,
ctqhPic1Date: Date,
ctqhPic1Sts: string,
ctqhPic2Cusno: string,
ctqhPic2Date: Date,
ctqhPic2Sts: string,
ctqhPic3Cusno: string,
ctqhPic3Date: Date,
ctqhPic3Sts: string,
ctqhCreateBy: null,
ctqhCreateDate: Date,
ctqhUpdateBy: string,
ctqhUpdateDate: Date,
ctqhNotes: string,
ctqhReason: string,
ctqhDlvrAddrId: number,
ctqhOrderId: string,
ctqhOrderDate: Date,
ctqhUpdateByAdmin: string,
ctqhUpdateDateAdmin: Date,
ctqhProductName:string,
ctqhQty:number
}