export interface VCustRegistration{
    ccregId: number,
    ccregAddress: string,
    ccregArea: string,
    ccregCityId: string,
    ccregEmail: string,
    ccregKecId: string,
    ccregKelId: string,
    ccregLongLat: string,
    ccregMinApproval: string,
    ccregMobilePhone: string,
    ccregName: string,
    ccregNationId: string,
    ccregNationImgFileName: string,
    ccregNikImage: string,
    ccregNibId: string,
    ccregNibImgFileName: string,
    ccregNibImage: string,
    ccregNickName: string,
    ccregPhone: string,
    ccregPic1Email: string,
    ccregPic1Name: string,
    ccregPic1Phone: string,
    ccregPic1password: string,
    ccregPic2Email: string,
    ccregPic2Name: string,
    ccregPic2Phone: string,
    ccregPic2password: string,
    ccregPic3Email: string,
    ccregPic3Name: string,
    ccregPic3Phone: string,
    ccregPic3password: string,
    ccregProvId: string,
    ccregRecvCmbaName: string,
    ccregRevcCmbaAccount: string,
    ccregRevcCmbaId: string,
    ccregRt: string ,
    ccregRw: string,
    ccregSentCmbaAccount: string,
    ccregSentCmbaId: string,
    ccregSentCmbaName: string,
    ccregZip: string
    
}