export interface DTORequestList{
    requestNo:string,
    requestDate: string,
    requestProductName: string,
    requestProductTypeName:string,
    requestProductPrice: number,
    requestProductDesc: string,
    requestProductAlias: string,
    requestProductSize: string,
    requestProductStock: number,
    requestProductMinPurc: number,
    requestProductImage1: string,
    requestProductImage2: string,
    requestProductImage3: string,
    requestProductImage4: string,
    requestSeqNo: string,
    requestNewProduct:string,
    requestSale:string,

}